### ISSUE TITLE
jump to queue index/item, hash-param for queue index

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-data-nav#13]
When navigating the queue and refreshing, the user gets sent back to queue index 1/X regardless of position before refresh.
It would be preferable if we could somehow restore the previous position in the queue.

However, just storing the index of the queue in the hash-param might not always be right, since the list itself will be refreshed and might have changed. (Item was previously at index 10, previous items got removed, item is now at index 7 but user ends up at index 10)

Also, if the user just acted on an item in the queue, which caused it to be removed from the queue, we should end up on the same index but another item. (Item was previously at index 10, item got removed, user ends up on index 10 - next item)

Both combined would be item at index 10, previous items got removed, item should have been at index 7 but got removed as well so user should end up at index 7.

Not sure how to solve this best.
One idea is to save the item id in hash-param and look for it when items change.
Although, since we don't have separate idList and items anymore, we lose the id when we get the item model.
However, to get to the index the item _would have had_ we need to save an adjacent (next?) id as a fallback id to jump to in case the primary id is missing.

We would also use this "jump" functionality in list/queue views where the user wants to jump to a specific item.

The base of it all might be to implement:

- [x] `selectIndex(queueIndex)`
- [ ] `selectIndexByItem(item)`
- [ ] `selectIndexById(id)`

**Comment by nomego** [comment]
`select(index)` is present in data-nav (untested though)

**Comment by plequang** [comment]
Using "hash parameter" feature provided by https://github.com/Neovici/cosmoz-data-nav/pull/36 solves the "refreshing" part of this issue.

`selectById(id)` already exists and has been partially tested.

The new "hash parameter" raises a ui/ux question when using this feature: assuming you're on the 3rd item in the queue, if you change the ordering of the data, then the current item might (will) be at another index in the queue. In that case, user will probably need a mean to jump quickly to another index or id.

This can be solved by using `selectById` when the data is bound to another list available in the UI, but maybe we want to have a something like "go to first"/"go to list" directly in `cosmoz-data-nav`.
