### ISSUE TITLE
When navigation to next item, component might display the wrong item temporarly

### ISSUE THREAD

**Issue by plequang** [Neovici/cosmoz-data-nav#3]
# Description

When navigation to next item, `cosmoz-data-nav` fires `need-data` event in order to get item data to display.  
If you are viewing item at index N, and you navigate quickly 3 times to next item, `cosmoz-data-nav` will display item at index N - 2  until `setItemById` has been called for the corresponding `need-data` event.

Also, if for some reason `setItemById` is not called, it seems `cosmoz-data-nav` will get stuck displaying the 3 items currently bound.

**Comment by megheaiulian** [comment]
@plequang With the changes in #2 this can't happen anymore but it is a requirement for `setItemById` to be called otherwise it will use old data.
Now a template's data is updated before animation starts.

**Comment by plequang** [comment]
We need an additional api call to instruct `cosmoz-data-nav`  that there was a failure when retrieving the data. 
Not sure what ` cosmoz-data-nav` should do in that case, but at least not display the old data.
We could display an error message, and maybe some mean to try to fire the ` need-data`  again.
@nomego what do you think ?

**Comment by megheaiulian** [comment]
@plequang  Normally request is made before it reaches the item. next button could be disabled with some properties and we could have a `readyData` boolean property to disable a tab containing the data-nav. I think we would need also a `readyTemplates` property to have the tab disabled when it has items but the 2 templates we use are not yet stamped.
