### ISSUE TITLE
Distribute state-changes across instances

### ISSUE THREAD

**Issue by nomego** [Neovici/cosmoz-data-nav#73]
From a UX-perspective, when a user loads an item in data-nav and activates a tab within that view, he would expect that the next item has the same tab activated.
This does kind of work when the tabs have hash-param features enabled, but since item 2 in data-nav is preloaded, it will only apply for item 1 and item 3 and onwards.

Data-nav needs some kind of generic mechanism to provide this signalling to other instances.

Maybe it could be enough for data-nav to fire some kind of `update-from-hash-params` event on the instance before activating it, which the hash-param handler can pick up on (cosmoz-page-location?) and redo the hash-param handling?

**Comment by cristinecula** [comment]
@nomego I used the [codeceptjs branch](https://github.com/Neovici/cosmoz-frontend/issues/1033) to add a failing test for this issue, from a UX perspective.

**Comment by cristinecula** [comment]
@nomego this should also be closed

**Comment by nomego** [comment]
Fixed by https://github.com/Neovici/cosmoz-tabs/pull/70
