### ISSUE TITLE
Item 1 is re-rendered when item 0 is removed.

### ISSUE THREAD

**Issue by cristinecula** [Neovici/cosmoz-data-nav#75]
> We are trying to make the workflow a bit more async, so when we get an 0K from backend we don't 
> force them to fetch new data.
> So if you're on item 1 in the queue and run a specific action and we get 200, we assume it shouldn't be in the queue anymore (and we don't have the info to show it) so we remove it from the omnitable list, which in turn removes it from data-nav and then we maintain the index (at 0).
> All that is working well.
> However, we get the message "data is updating", which data-nav prints when we're rendering a template afaik and I have a theory that the "isIncomplete" gets confused, since the pre-rendered template at index 1 is now at index O, so we re-render it while the user is looking and get the "data is updating" message.
> Maybe we can make data-nav realize that the instance for the item at index O actually is the template at index 1.

Reproduction:
1. fill a data-nav with complete `items`
2. remove item 0
3. item 1 will become item 0 and so on
4. data-nav will re-render instance 0 to display item 1
instead data-nav should have moved instance 1 in place, since it already has rendered item 1

**Comment by cristinecula** [comment]
@nomego It would really help me if you could add a reproduction scenario for this issue on cosmoz-frontend.

**Comment by nomego** [comment]
Check if your rights allows you to go to /purchase/invoices/list-queue-preapproval-and-approval and find an invoice with "Preapprove and approve".

**Comment by nomego** [comment]
Fixed by #80
